name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe it below.
  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: What problem does this solve? Why would it be useful?
      placeholder: I'm frustrated when...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
      placeholder: Describe the feature in detail...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you've thought about?
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Where would this apply?
      options:
        - Frontend (Gantt chart, UI)
        - Backend / API
        - Mobile app
        - Auth / Users
        - Tasks / Projects / Categories
        - IoT API
        - Admin
        - Other
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority (your view)
      description: How important is this to you?
      options:
        - Nice to have
        - Would improve my workflow
        - Important / blocking
